name: cam-gan
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cudatoolkit=11.1.74
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.3.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - python=3.8.11
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.9.1
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - charset-normalizer==3.1.0
      - filelock==3.13.4
      - fsspec==2024.3.1
      - idna==3.4
      - jinja2==3.1.3
      - jsonpatch==1.33
      - jsonpointer==2.4
      - lightning-utilities==0.11.2
      - lmdb==1.4.0
      - lpips==0.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.0
      - pillow==9.5.0
      - pip==24.0
      - protobuf==3.20.1
      - pytorch-fid==0.3.0
      - pyyaml==5.4.1
      - requests==2.31.0
      - scipy==1.10.0
      - sympy==1.12
      - tensorboardx==2.5.1
      - torch==2.3.0
      - torchmetrics==1.3.2
      - torchvision==0.18.0
      - tornado==6.4
      - tqdm==4.64.1
      - triton==2.3.0
      - typing-extensions==4.11.0
      - urllib3==2.0.3
      - visdom==0.2.4
      - viz==0.0.5
      - websocket-client==1.7.0
prefix: /hpc/home/munsif.ali/.conda/envs/cam-gan
